[package]
name = "nextpage"
version = "0.1.0"
authors = ["alexander.burkov <alexander.burkov@jetbrains.com>"]
edition = "2018"

[dependencies]
clipboard = "0.5.0"
spinners = "1.0.0"
reqwest = "0.9.11"
dirs = "1.0.5"
byteorder = "1.3.1"
scraper = "0.9.1"

